[package]
name = "orr_desktop"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
dirs = "6.0.0"
muda = "0.19.3"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tray-icon = "0.24.2"
windows-sys = { version = "0.61.2", features = ["Win32_Foundation", "Win32_Graphics_Gdi", "Win32_UI_WindowsAndMessaging", "Win32_UI_Input_KeyboardAndMouse", "Win32_System_LibraryLoader"] }
winit = "0.30"

[profile.release]
opt-level = 3
lto = "thin"
strip = true
